### ISSUE TITLE
No albums were found

### ISSUE THREAD

**Issue by michaelrogalewski** [andyjsmith/SmugMug-Downloader#1]
The last few days I am getting this for every user I try:

"No albums were found for the user (username). The user may not exist or may be password protected."

Tried for multiple users and they were definitely working a week ago

**Comment by monhee** [comment]
I'm seeing the same problem. It seems smugmug has changed the html structure causing the web scraper to miss the albums.

**Comment by andyjsmith** [comment]
Issue should be fixed. There was a slight change in the response format, just an additional element that was being selected instead of the proper JSON response.
