### ISSUE TITLE
user may not exist or password protected 

### ISSUE THREAD

**Issue by jbmcclain** [andyjsmith/SmugMug-Downloader#2]
Hi, I have tried this several times.  I have logged into my smugmug account and grabbed my ssms cookie but still get the issue.   i have even turned the site lock off so there is only one main password to get the account.  any thoughts or suggestions?

Thank you

**Comment by jbmcclain** [comment]
Sorry this can be closed i figured out what my issue was

**Comment by andyjsmith** [comment]
Glad you could fix the issue.

**Comment by jbmcclain** [comment]
Hi @andyjsmith is there a limit on how many photos or folders? I have about 1.82 Terabytes and it seams to fail @ just bellow 100 meg but i believe it is getting all my gallery names

**Comment by andyjsmith** [comment]
I am not aware of a limit but I have never tried that much data before. You may be hitting a rate limit on SmugMug.
