### ISSUE TITLE
Sub-Album

### ISSUE THREAD

**Issue by jocklover** [andyjsmith/SmugMug-Downloader#21]
How do I designate a sub-album? Target SM user has a large album folder and I want to download an album / album tree inside the folder. 
I understand that the --album argument exists, but not sure how to designate the sub-album.
Thanks,

**Comment by patrickxia** [comment]
Just attach it to USERNAME. If you're at USERNAME.smugmug.com/a/b/c, you can just do USERNAME/a/b/c. I sent https://github.com/andyjsmith/SmugMug-Downloader/pull/24/files to add this to the documentation.
