### ISSUE TITLE
Downloaded files empty

### ISSUE THREAD

**Issue by markpalotas** [andyjsmith/SmugMug-Downloader#7]
Hello there,
first of all thanks a lot for sharing this downloader!

I've just started experimenting with it and from the terminal output it would seem I successfully got it to work; album list is downloaded, output directories are created and I can see how the file download progresses, too, and the process closes with a "Completed" message.
When I check the actual files, however, they don't have any content - the correct number of files is created, with the correct file names, but the size is 0 for each one of them, they are just plain empty.

Do you maybe have an idea where the problem might be?

Thank you!
mark

![image](https://user-images.githubusercontent.com/43383306/104786127-6961ff00-578c-11eb-96d1-d5a77a718ade.png)

![image](https://user-images.githubusercontent.com/43383306/104786154-7c74cf00-578c-11eb-8f09-4326205884a1.png)

**Comment by andyjsmith** [comment]
Hmm I'm not really sure. I just verified that the script still works normally. Maybe the account has some security settings on the albums that prevents it from actually downloading it.

**Comment by markpalotas** [comment]
Thanks for getting back! Will check into that and experiment around a bit more - and let you know if/when I figure out what's the matter

**Comment by markpalotas** [comment]
You were right - the culprit was a security setting. My galleries were all set to unlisted so that only people with the specific link could view them, plus there were additional passwords set for the various folders.
Once I removed those, the issue was gone!
Thanks again :)
