### ISSUE TITLE
Syntax Error in line 78 and line 97

### ISSUE THREAD

**Issue by lulzkillergithub** [andyjsmith/SmugMug-Downloader#8]
Good morning.

py -3 gets me this error:

File "smdl.py", line 78
    desc=f"{fg('yellow')}{attr('bold')}{format_label('All Albums')}{attr('reset')}"):

the error in question is the last " mark. I imagine it's a tqdm version mismatch, but it could be something else.

Thanks you.

**Comment by andyjsmith** [comment]
Can you post the entire error output?

**Comment by lulzkillergithub** [comment]
Sorry about that, pasted after I tried troubleshooting. And yes it's terse, unless there's something I'm missing.

```
$ py -3 smdl.py -u USERNAME
  File "smdl.py", line 78
    desc=f"{fg('yellow')}{attr('bold')}{format_label('All Albums')}{attr('reset')}"):
                                                                                  ^
SyntaxError: invalid syntax
```

**Comment by andyjsmith** [comment]
Can you let me know what version you're using? `py --version`

And what OS you're using.

I understand you might not want to reveal the username of who you're downloading, so can you test it on the user "thomashawk" (random public account I found). That user works for me so if it does for you too then we know its an issue with the user you're downloading, not the script itself.

**Comment by lulzkillergithub** [comment]
I was using the py -3 flag to run that version, but I guess my two python installs were really messed up. I nuked both installs, freshly installed only 3.9.2, and fixed some environmental paths, and the script is now running perfectly. I appreciate the response, closing.
